name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.2.11f1
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

      # Activate unity
      - name: Activate Unity
        run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      # Run edit mode tests
      - name: Run edit mode tests
        run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -projectPath . -runTests -testResults ./testresults.xml